### ISSUE TITLE
Schema method incuding unlock_system_properties_once() fails on Entity of Type File

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#451] opened 2016-04-26 14:50 UTC
Discovered when resolving inability to change type attribute of entity see #450 

Unfortunately trying to use the unlock_system_properties_once() causes the following error when added to a schema method on File.

```
(
unlock_system_properties_once(this),
set_privileged(this, 'type', 'Font')
)
```

```
java.lang.UnsupportedOperationException: Active save actions are not supported for overridable types.
        at org.structr.schema.SchemaHelper.formatDynamicSaveActions(SchemaHelper.java:902)
        at org.structr.core.entity.SchemaNode.getAuxiliarySource(SchemaNode.java:497)
        at org.structr.schema.SchemaService.reloadSchema(SchemaService.java:107)
        at org.structr.schema.SchemaHelper.reloadSchema(SchemaHelper.java:301)
        at org.structr.schema.ReloadSchema.execute(ReloadSchema.java:34)
        at org.structr.core.graph.ModificationQueue.doPostProcessing(ModificationQueue.java:127)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:115)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.rest.servlet.JsonRestServlet.doPost(JsonRestServlet.java:433)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:55)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.AsyncGzipFilter.doFilter(AsyncGzipFilter.java:408)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

I tried a variety of permutations and couldn't get any to take on recompile

Additionally was able to determine that this _did_ work with a regular `AbstractNode` but not `File`.

**Comment by vigorouscoding** [comment] 2016-04-28 11:43
I don't understand 100%. Is the problem that the schema does not recompile and thus the custom method is not useable. (The stacktrace suggests that the schema is recompiling but that should not happen unless a `SchemaReloadingNode` is being edited.)

For further clarification, what is the name of the custom method? And you created that method on the class `File`, correct?
I would like to reproduce this on my system to provide a fix for this ASAP.
Thank you!

**Comment by eric-schleicher** [comment] 2016-04-28 18:52
This was in the method tab of the entity editor for type 'file'.  I believe
the name used was 'reclassify' or something innocuous and intentionally NOT
a java keyword.

Produces red flash on recompile and that stack trace.   You should be able
to reproduce with that method code on 'File'

I don't understand 100%. Is the problem that the schema does not recompile
and thus the custom method is not useable. (The stacktrace suggests that
the schema is recompiling but that should not happen unless a
SchemaReloadingNode is being edited.)

For further clarification, what is the name of the custom method? And you
created that method on the class File, correct?
I would like to reproduce this on my system to provide a fix for this ASAP.
Thank you!

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/structr/structr/issues/451#issuecomment-215398799>

**Comment by eric-schleicher** [comment] 2016-05-11 00:52
@vigorouscoding, underliying the issue highlighted here, was the need to (thoughtfully) change a nodes Type.  I've thought about it considerably, and the approach of an specific entity method to change the it's type is a dead-end given the need for all the modeling overhead (superfluous entity methods).  While it's possible, IMHO the ability to do this should not be limited to StructrScript or be specifically coded into the schema.

I'll leave this open if you like (since it's does look like a bug), but I'm moving on to solve the problem.  a solution has force the issue to move up the creation of a new process that just creates the entity in the right class when it's uploaded, obviating the need to re-classifly it.

**Comment by amorgner** [comment] 2016-05-11 01:16
@eric-schleicher It's a bug, very easy to reproduce just by adding any method with any code (even `()` does the trick).
We'll fix is asap.

**Comment by eric-schleicher** [comment] 2016-05-11 01:20
@amorgner 

Thanks, the thrust of my point was that while changing types is understandably a higher risk behavior in the system, removing the ability for an administrator to perform the action through the UI is to the potential dis-benefit of the system owner.

**Comment by amorgner** [comment] 2016-05-11 18:34
@eric-schleicher It's not related to `unlock_system_properties_once`, the problem is the built-in `File` type itself. Adding custom schema methods to `File` is not supported at the moment, and it's difficult to resolve.

There's a workaround: Just create your own File base class, e.g. `BaseFile`, extend `org.structr.dynamic.File`, add the method to `BaseFile`, and let your other File types extend `BaseFile`.

**Comment by eric-schleicher** [comment] 2016-05-12 03:35
OK will take a look at it.  the generic base64data attribute in #452 largely obviated the need for methods on the base file.  coincidentally all of me entity method _just_ happen to be on the classes that extend file.

**Comment by amorgner** [comment] 2016-05-17 19:06
Finally merged the changes to fix this bug into master. Snapshot will be deployed soon.

**Comment by amorgner** [comment] 2016-05-18 15:33
Latest snapshot is available at https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/2.0.2-SNAPSHOT/.

**Comment by eric-schleicher** [comment] 2016-05-19 22:26
Thanks @amorgner .  looking to get current, but need to resolve issue restoring snapshot in #459 before updating.

**Comment by vigorouscoding** [comment] 2017-01-13 09:26
I'm closing this as this has been fixed

**Closed by vigorouscoding** 2017-01-13 09:26 UTC
Labels: bug, fixed / waiting for confirmation
