### ISSUE TITLE
[structr-ui] [2.1.0-SNAPSHOT-201611142119] Proxy not working after parsing when importing template

### ISSUE THREAD

**Issue by ackward** [structr/structr#481] opened 2016-11-18 14:38 UTC
Using cntlm (http://cntlm.sourceforge.net/) as proxy/ntlm wrapper to websense proxy (now Forcepoint https://en.wikipedia.org/wiki/Forcepoint).

In structr.conf it's configured as:

> application.proxy.http.url = http://<cntlm ip>:3128

When importing a Page template, following the started guide I tried "http://getbootstrap.com/examples/jumbotron" the page is accesed and downloaded but when it's parsed and tries to download associated media, styles,... fails with timeout because Structr goes directly instead of using the proxy.

The proxy log shows:

> cntlm: PID 9476: 10.0.1.15 GET http://getbootstrap.com/examples/jumbotron/

And the structr log (some info is in Spanish sorry, "La red is inaccesible == network is unreachable")

> 2016-11-18 15:04:13 [qtp1524961826-27] INFO  org.structr.web.importer.Importer - ##### Start fetching http://getbootstrap.com/examples/jumbotron/ for page jumbotron #####
> 2016-11-18 15:04:13 [qtp1524961826-27] INFO  o.s.websocket.command.ImportCommand - Successfully parsed http://getbootstrap.com/examples/jumbotron/
> 2016-11-18 15:04:15 [qtp1524961826-27] INFO  org.structr.web.importer.Importer - Starting download from http://getbootstrap.com/favicon.ico
> 2016-11-18 15:04:15 [qtp1524961826-27] INFO  org.structr.web.importer.Importer - Downloading from http://getbootstrap.com/favicon.ico
> nov 18, 2016 3:08:30 PM org.apache.http.impl.execchain.RetryExec execute
> INFORMACIÓN: I/O exception (java.net.SocketException) caught when processing request to {}->http://getbootstrap.com:80: La red es inaccesible (connect failed)
> nov 18, 2016 3:08:30 PM org.apache.http.impl.execchain.RetryExec execute
> INFORMACIÓN: Retrying request to {}->http://getbootstrap.com:80
> nov 18, 2016 3:12:44 PM org.apache.http.impl.execchain.RetryExec execute
> INFORMACIÓN: I/O exception (java.net.SocketException) caught when processing request to {}->http://getbootstrap.com:80: La red es inaccesible (connect failed)
>

**Comment by vigorouscoding** [comment] 2016-11-21 11:56
I just pushed code that should fix this problem. The importer now uses the proxy configuration for resources as well as for the main page. (see d4a32de9d0de7bb195b6a7a3d1d3a2a8ed1af02d).

This will be included in the next snapshot release. If you are building structr from source you can just pull the current master and test the fix.

I'm looking forward to hearing that the issue is resolved :)

**Comment by ackward** [comment] 2016-11-23 14:08
It's working or at least it seems to be.

I have downloaded the code and compile it. I had an error in runtime due to a missing library.

```
2016-11-23 14:35:26 [main] ERROR org.structr.schema.SchemaService - Unable to compile dynamic schema.
java.lang.NoClassDefFoundError: org/odftoolkit/odfdom/doc/table/OdfTable
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
```
It seems like the odftoolkit java library was missing:

`cp odftoolkit-0.6.1-incubating/odfdom-java-0.8.10-incubating.jar structr/structr-ui/target/lib/`

After that I was able to run and login without problems and import the jumbotron example. The only issue has been accessing jquery:

```
org.structr.common.error.FrameworkException: Unable to fetch file content from address https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.structr.rest.common.HttpHelper.streamURLToFile(HttpHelper.java:386)
```

But the issue I'm sure is with websense (corporate proxy) because it hijacks the google cert and uses a cert issued by " Forcepoint Cloud Web Enforcer CA" instead. Adding that CA to the java cacerts should be enough to fix it.

And the proxy really logs structr trying that connection:

> cntlm: PID 3740: 10.0.0.15 CONNECT ajax.googleapis.com:443

Anyway, the page is parsed and imported:

![image](https://cloud.githubusercontent.com/assets/9418324/20564358/318c2820-b18d-11e6-9ade-9e1a0164ef09.png)

**Comment by vigorouscoding** [comment] 2016-11-24 12:23
Glad to hear that the import itself now works - except for the certificate hijacking mess the corporate proxy causes! I'll close this issue for now as the original problem has been fixed.
Thank you for helping us improve structr! :)

Concerning the error message about the dynamic schema not being able to compile: This usually only happens when switching between structr editions (i.e. from enterprise to community).
If this error pops up again it would be helpful if you could open a new issue with the log output and a description of your setup. Thank you!

**Closed by vigorouscoding** 2016-11-24 12:23 UTC
Labels: fixed / waiting for confirmation
