### ISSUE TITLE
2.0 Snapshot 1 Filesystem manager does not show Entities inheriting from Type:File created in previous version

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#405] opened 2015-10-23 23:55 UTC
This behavior was observed previously (in 1.1 snapshots) as well.

But if a have an entity type that inherits from file...  when nodes are created they do no become visible in the file manager.

At the moment.  I create them as file and then change their type, but in doing so, they dissapear.  I can request them as expected, but they're just hidden.

In my Case I have MachinableTemplate which Inherits Type: File.

**Comment by vigorouscoding** [comment] 2015-10-24 02:48
Hi Eric,

I can't reproduce your problems. I just created a types "SpecialFile"
and  "MachinableTemplate"
inheriting from "org.structr.dynamic.File" and
"org.structr.web.entity.FileBase" respectively.
They both appear in the Filesystem area. What exactly is your
"MachinableTemplate"
extending - which fully qualified classname?

[image: Inline-Bild 1]


Best,
Kai

2015-10-23 16:55 GMT-07:00 Eric Schleicher <notifications@github.com>:

**Comment by eric-schleicher** [comment] 2015-10-27 22:00
Machinable Template Extends File:  here are MachinableTemplate entries

*figure 1*
![image](https://cloud.githubusercontent.com/assets/8261783/10773784/b07c9b00-7cba-11e5-9a3d-3579d9f53682.png)

**note**:  all of these assets are in the root ``` / ``` folder of the filesystem.


*figure 2.*and a screen shot of the filemanager view showing that only two of the MachinableTemplate.  The two that are down i manually changed their type ('back' to file and then immediately back to 'MachinableTemplate' ) by getting the node dialog editor open from #Crud via a related node.

I think this may be a labeling issue, as it's known that they are not preserved on import as in #393 

![image](https://cloud.githubusercontent.com/assets/8261783/10773743/6b5d5fc8-7cba-11e5-8fb7-0a44c2f07eed.png)

**Comment by amorgner** [comment] 2016-03-01 08:14
I could reproduce this behaviour. What I tested:

- Created a new type in Schema editor `MachinableTemplate`
![screen_188](https://cloud.githubusercontent.com/assets/291266/13421024/86fcd608-df8b-11e5-8ef6-a5c50a8e7e44.png)

- Created a couple of instances in CRUD
![screen_189](https://cloud.githubusercontent.com/assets/291266/13421041/abea284e-df8b-11e5-97e0-046bf54050c1.png)

They are listed in the Filesystem area:

![screen_187](https://cloud.githubusercontent.com/assets/291266/13421053/c623d6ba-df8b-11e5-9436-09bcef6736b9.png)

Then I exported the whole database with `post maintenance/sync '{mode:export, file:export1.zip}'` and started an empty database instance with the `export1.zip` renamed to `seed.zip`. When re-imported with the backup/sync tool, the `MachinableTemplate` instances were **NOT** visible in the Filesystem.

@eric-schleicher We'll look into this issue now and report back.

Please note: It is not possible anymore to change the type of an existing entity via UI or REST API as we introduced **System Properties**. However, there's a way to modify system properties but only programatically using the `unlock_system_properties_once()` function (see https://support.structr.com/article/403).

**Comment by amorgner** [comment] 2016-03-01 08:21
@eric-schleicher You can fix it by rebuilding the index after import. Just do a `post maintenance/rebuildIndex '{type:MachinableTemplate,mode:nodesOnly}'` and you'll see all custom files again.

We'll add the re-indexing to the import command so that it will happen automatically in future versions of Structr.

**Comment by amorgner** [comment] 2016-03-01 18:23
Should be fixed by e8b7930.

**Comment by amorgner** [comment] 2016-03-01 22:37
New snapshot is deployed.

**Closed** 2016-03-03 19:21 UTC
