### ISSUE TITLE
No key-value mapping of parameters in Method Calls

### ISSUE THREAD

**Issue by l-1** [structr/structr#467] opened 2016-07-18 23:20 UTC
I've tested this on a clean install of Structr 2.0.1 stable release.

In article https://support.structr.com/article/128 example says

> `${call('methodName', 'param1', 'value1', 'param2', 'value2')}`

In another article https://support.structr.com/article/192

> If we are only interested in a single parameter we can use the following code to retrieve it.
> 
> ```
> {
>   var singleParam = Structr.retrieve('parameterName');
> }
> ```
> 
> If we want to retrieve all the parameters there is a special Structr.vars object which contains all parameters as a map indexed by the parameter name.
> 
> ```
> {
>   var singleParam = Structr.vars;
>   /*
>   singleParam now contains the object
>   {
>       param1: "Test",
>       param2: 12
>   }
>   */
> }
> ```
### My code and logs:

Method **toCall**:
    `call('toLog','p1','param1!','p2',now,'p3',this.id)`

Method **toLog**:

```
{
    var r = Structr.retrieve('1');
    var sP = Structr.vars;
    var js = JSON.stringify(sP);
    var me = Structr.me;
    Structr.log('called\n', js, '\t arg: ', r,'\t me: ', me);
}
```

Log:

> INFO: called
> {"0":"p1","1":"param1!","2":"p2","3":"2016-07-17T12:22:32+0300","4":"p3","5":"adbeebe47fbf4416b2d0abb8a4c8bca4"}
>  arg: param1!    me: org.structr.core.entity.SuperUser@1365d3af

As you can see, parameter's names are just values and keys are numbers.

**Comment by vigorouscoding** [comment] 2016-12-09 09:14
**Thank you for your excellent bug report**! And *sorry for taking so long to respond*.

I can confirm the described behavior and also confirm that it is wrong.

I will see to it that this is fixed as soon as possible and I will report back here when it is done with an update and a short list on how to upgrade existing applications.

**Comment by vigorouscoding** [comment] 2016-12-11 12:16
I fixed the bug with commit 6377ba05d69d82091d333e41abd1bbf656138ec3. type-less schema methods now use named parameters instead of numerically indexed ones. If you are building from master you can pull the newest code - if you are using the snapshots, the next snapshot will contain the fix.

**Thanks again for your excellent bug report!** Fixing this one was a breeze using your minimal example! :)

I'll leave this issue open so you can check out the new behavior and close this issue :)

#### One thing to note

As you might have noticed in your original bug report, accessing "Structr.me" results in something like `me: org.structr.core.entity.SuperUser@1e83313d`
This is due to the fact the type-less schema methods are (currently) always run in a SuperUser-Context.


####  Updating existing Structr instances would work like this:

If you are using type-less schema methods in existing Structr instances you would need to update them. Hopefully you used the call-function as it was intended (`call('toLog','p1','param1!','p2',now,'p3',this.id)`) because then you simply need to replace `retrieve('1')` with `retrieve('p1')` and `retrieve('3')` with `retrieve('p2')` etc and you are done.
If you called your type-less methods with parameter values only you would need to update the method itself **AND** all the places the method is called from.

**Comment by vigorouscoding** [comment] 2017-01-13 09:27
I'll close this as the issue has been fixed - thanks again for the bug report and the steps to reproduce!

**Closed by vigorouscoding** 2017-01-13 09:27 UTC
Labels: fixed / waiting for confirmation

**Comment by l-1** [comment] 2017-01-23 13:00
Yes, sorry, hadn't had the chance to update structr and check it yet.
From the looks of it, the issue has been fixed, but I will report back as soon as I get the chance to check it out.
Thanks!
