### ISSUE TITLE
Improvement: allow multiple changes per compile when editing attributes in views

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#449] opened 2016-04-20 09:40 UTC
![image](https://cloud.githubusercontent.com/assets/8261783/14670049/534a090c-06a0-11e6-8ed4-380aa843a61f.png)

It would be nice to "edit" the set of columns in a view without having to (re)compile for each one.  I think the existing pattern of chiclets to name match the column as the user is typing is great...  but right now it takes an inordinate amount of time to add a single view with 8-10 attributes on an instance with ~150 in the model.  This takes about 2 minutes: That's about 5-7 second for the compile time for each attribute being added to the view, and then another 4-5 seconds just to let the UI settle (to be safe).  

Ideally the commit of the addition(s) would be until the user explicitly says "yes/confirm", then a compile/validate event  would happen, but for the combines set of attributes (since they're prevalidated with the chiclets).

On most machines, a model with ~150 entities in recent build

**Comment by eric-schleicher** [comment] 2016-04-20 09:41
obviously not a priority :)

**Comment by amorgner** [comment] 2016-06-21 14:46
At least for new attributes, there are icons to save and cancel the action now. It's in the `distributions` branch and not yet merged into `master`. Will probably be included in release 2.1.

**Comment by cmorgner** [comment] 2016-09-27 14:36
The feature should be available in the latest snapshot, please review and close this issue. Thank you!

**Comment by vigorouscoding** [comment] 2017-01-13 09:23
I'll close this because this works and the issue is rather old

**Closed by vigorouscoding** 2017-01-13 09:23 UTC
Labels: feature request, fixed / waiting for confirmation
