### ISSUE TITLE
Missing Relationship Properties while exporting to CSV 

### ISSUE THREAD

**Issue by ShaharKatz** [structr/structr#490] opened 2017-02-28 12:42 UTC
Hey, 

I've done the example in the tutorial (Project, ProjectMember) and exported the data to CSV format from the "data" page. The resulting file contained the correct nodes and their local properties but ingoing and outgoing relationships were changed to [object Object], is there a way to pass the relationships as well?

Thanks,

SK

**Comment by vigorouscoding** [comment] 2017-03-01 14:42
Thank you for your error report! I can confirm that the Export/Import CSV function in the "Data" section are not working as intended at the moment. We are working on a fix for this.

While we are working on a fix, you can alternatively use the CSV servlet. It supports the same parameters as the REST servlet.

Just navigate to one of the following (or modify the URLs as needed)

- http://localhost:8082/structr/csv/Project
- http://localhost:8082/structr/csv/Project/ui    (to serialize the "ui" view)
- http://localhost:8082/structr/csv/Project/ui?pageSize=10&page=1  (to serialize the first ten objects using the "ui" view)

Hope that helps for now!

**Comment by vigorouscoding** [comment] 2017-03-22 09:33
We just recently fixed this issue in the current master. Collections are now serialized correctly (as encoded lists of IDs of related objects).
If you are running snapshot builds you will have to wait for the next snapshots, if you are compiling from source you can pull the newest code and see for yourself.

As a sidenote: The collections of remote objects are serialized as a list of IDs of those remote objects, not as a list of relationships. Therefor, if your relationships have non-standard properties, you need to export the relationships themself as CSV (also works via the data section).

I'll leave this issue open for the time being. Feel free to close it :)

**Comment by vigorouscoding** [comment] 2017-06-26 14:04
I'll close this now as it has been fixed for a while - please reopen if you find a bug with the current master and thanks for reporting!

**Closed by vigorouscoding** 2017-06-26 14:04 UTC
Labels: bug, fixed / waiting for confirmation
