### ISSUE TITLE
After successfull build i get 19:46:16.423 [main] INFO  org.structr.core.app.StructrApp - 0 service(s) processed

### ISSUE THREAD

**Issue by fatjoni** [structr/structr#514] opened 2018-02-03 18:52 UTC
After a successful build in UBUNTU ENV, i run it through mvn validate exec:exec and get  "Initialization complete" but nothing shows on localhost:8082/structr and i notice that it says at the terminal 0 services processed while when i try to run it through the prebuilt binary i have i think 4 services running.

Can you please help me?

Thanks

**Comment by fatjoni** [comment] 2018-02-05 17:17
I have tried to build both the 2.3 version and the version 3.0 in both ubuntu and windows. I have only removed the line for pushing the docker image to the official repository since obviously i dont need that.
Please let me know what might be the issue.
Thanks

**Comment by yungchunglin** [comment] 2018-04-03 17:15
Same issue here.  I built 2.3.8.
My env is Mac OS X.  It says initialization complete, but it says 0 service(s) processed

**Comment by vigorouscoding** [comment] 2018-04-09 12:43
This has been discussed in the Structr Google Group (see this thread/message: https://groups.google.com/d/msg/structr/Jv4p6jAZXDs/gz9pfGfEBAAJ ).

> When we introduced the new licensing model, we decided to use code signing to sign the core JAR and all our modules. With that change, Structr does not load unsigned modules any more, so while you can still build Structr from source, you won't be able to run it without the code signing key. 
>
> We recommend to use the pre-compiled binaries available at https://structr.org/download 
>
> Sorry, I have to correct my previous post: you don't need the code signing key to _run_ Structr, but to _build_ it, so you won't be able to run a Structr version that was _built_ without the code-signing key.

I'll close this as this is intended behavior

**Closed by vigorouscoding** 2018-04-09 12:43 UTC
Labels: question
