### ISSUE TITLE
Service start command is not aware of failure to start database

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#383] opened 2015-08-25 15:00 UTC
I've been experiencing intermittent corruption of my store.  We become aware of the corruption on restart of structr.  when starting the structr-ui service the command succeeds, but if the database fails to initialize there is no indication that the complete structr application is in an error state.  

The last line in the log file reads initializing database.... no additional entries are logged.

it would seem that the startup script should have some hook to the successful start of the neo4j service...  either in the structr log, expressing reporting a failure to start.

**Comment by amorgner** [comment] 2015-08-25 15:33
Did you upgrade to the latest snapshot which includes Neo4j 2.2.4?

**Comment by eric-schleicher** [comment] 2015-08-26 14:45
This issue created just because structr is unaware of a database failure to
start scenario

**Comment by amorgner** [comment] 2015-08-26 15:11
This is not fully true, as the described behavior was caused by a nasty bug in Neo4j 2.2.3 producing an infinite loop. In this rare case Structr doesn't get any information about the status of the recovery process from Neo4j (see description of the fix here: https://github.com/neo4j/neo4j/commit/c9596af0d990d7dde9a9053799b7295985ae3c05)

In different cases, for instance if the startup fails due to ``allow_store_upgrade=true`` not being set, or other things Neo4j complains about, Structr's startup routine stops and does not start the server.

The only way we could deal with it is to set a timeout, but how long should it be? Large databases on slow disks sometimes need hours to recover. Setting a too small timeout would effectively prevent such databases from recovering.

I'd rather not introduce a timeout due to above reasons, so closing this one.

**Closed by amorgner** 2015-08-26 15:11 UTC

**Comment by eric-schleicher** [comment] 2015-08-27 05:07
Ok..... structr was unable to message on the condition... glad to see that the underlying issue with neo has been addressed.
