### ISSUE TITLE
How to save as web app

### ISSUE THREAD

**Issue by erikobox** [structr/structr#536] opened 2019-10-17 07:16 UTC
How to export website and publish under my domain name and accessible from the web. Also, if the answer is: Structr is an engine, then how to remove port numbers from the URL?

**Comment by vigorouscoding** [comment] 2021-02-24 08:08
This issue got forgotten somehow - even though it is pretty old I'll add a bit of information and close it. As this is not a bug the proper place for this kind of question would be the [Structr Google Group](https://groups.google.com/g/structr)

----

Structr is a runtime - you can install it along with your application on any server capable of running java (or GraalVM in more recent snapshots). See https://docs.structr.com/docs/running-structr#installation for info about installing structr.

To export your application from your local development environment and transfer it to the structr server you can use the builtin deplyoment export and import. You can use this from the dashboard or via REST/admin console (see [Dashboard](https://docs.structr.com/docs/the-dashboard#deployment) , [Deployment Import](https://docs.structr.com/docs/fundamental-concepts#deployment-import), [Deployment Export](https://docs.structr.com/docs/fundamental-concepts#deployment-export))

The ports can be configured in structr.conf using [these keys](https://docs.structr.com/docs/configuration-settings#interfaces) either directly via structr.conf or using the [configuration tool](https://docs.structr.com/docs/configuration#configuration-tool)

**Closed by vigorouscoding** 2021-02-24 08:08 UTC
