### ISSUE TITLE
graphviz : rel/ nodetype selectors are gone.

### ISSUE THREAD

**Issue by ophileon** [structr/structr#107] opened 2014-02-26 16:44 UTC
When you leave the viz, e.g. to go to the data page, and go back to the graphviz, the selectors are gone.

**Comment by vigorouscoding** [comment] 2015-12-23 09:28
I think this issue has been resolved for a while now. I just tested and could not reproduce the error.
@ophileon  Could you retest this in a recent build and report back here?

**Comment by vigorouscoding** [comment] 2016-01-05 12:09
I think we'll close this one as the graph section has evolved quite a bit and the issue seems to be corrected

**Closed by vigorouscoding** 2016-01-05 12:09 UTC
Labels: bug, ui
