### ISSUE TITLE
Bug or Quirk: 500 with no reason as to why when body includes remoteRelationship that does not exist

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#424] opened 2016-01-16 04:05 UTC
Spent more than a few minutes trying to track down a 500 error when POSTing to create a new entity.

It took a while to find, but sillyme...  I had an extra sub-structure that i'm sure Structr was trying to find a remote attribute for.

the problem was the error code was:
{
    "code": 500
}

So brief with no indication

I watch both the web log and the main log when running these operations and NOTHING....

Seems like "remoteAttribute not not found in model" may be within reason for internal checking?  could have gotten an error clearly describing the issue.

**Comment by cmorgner** [comment] 2016-01-21 10:55
Closing this issue since it is a duplicate of #413.

**Closed by cmorgner** 2016-01-21 10:55 UTC
