### ISSUE TITLE
missing buildNumber in the doc

### ISSUE THREAD

**Issue by Mog83** [structr/structr#361] opened 2015-04-17 07:46 UTC
Hi

I've followed the doc but when I'm building the app with maven I have to add `-DbuildNumber=...` otherwise the build fail.

Good job!

**Comment by amorgner** [comment] 2015-04-17 08:34
Can you please elaborate?

What was the exact command you used? Which version (commit ID)? Which OS?

**Comment by Mog83** [comment] 2015-04-17 08:57
Oups sorry

So windows 8
Jdk 7ish
I'll check the version (cloned it this morning) and I'll grab the stack
trace as well as soon as I'm back on my desktop.

**Comment by shoreflyer** [comment] 2015-05-13 12:50
I have a similar problem with a fresh checkout of the code: I need to add -Dmaven.javadoc.skip=true otherwise I get a load of javadoc errors and build fails.
The next failure is in the structr-ui directory; the missing build number during exec:exec because artefacts cannot be found...
I'm on MacOS running JDK 1.8 and mvn 3.3.3

**Comment by amorgner** [comment] 2015-05-13 13:00
Please use JDK 1.7 and Maven 3.0, JDK 1.8 is not supported.

Windows is also not officially supported at the moment.

**Comment by shoreflyer** [comment] 2015-05-13 13:16
I understand the reasons the javadoc would fail during the build because of the 1.7 and 1.8 differences, I don't understand how the maven versions relate to the build time stamps being off by an increment and hence the files/modules cannot be found. Just as an example, one of the files generated was structr-ui-1.1-SNAPSHOT-201505131253.1.jar but as you can see above it is looking for structr-ui-1.1-SNAPSHOT-201505131254.1.jar...

I'm going to spin up a vanilla vagrant ubuntu instance with the versions you have specified to test...

**Comment by amorgner** [comment] 2015-05-13 13:38
Confirmed, ``mvn exec:exec`` doesn't work (anymore).

Please use the run scripts, like ``run_debug.sh`` instead for now.

**Comment by amorgner** [comment] 2015-05-13 14:16
Made ``mvn exec:exec`` execute ``run_debug.sh`` now: 289b28f2932a13fd3d9cfbf2719b0866a9dba178

Does that fix your issue?

**Comment by shoreflyer** [comment] 2015-05-13 14:27
This does indeed fix my issue, thanks!
All though admin/admin doesn't work as per documentation...

**Comment by shoreflyer** [comment] 2015-05-13 14:28
MATCH (n:`User`) RETURN n LIMIT 25 in Neo returns 0 results... some init issue with the data?

**Comment by shoreflyer** [comment] 2015-05-13 14:40
May 13, 2015 4:39:25 PM org.structr.core.auth.AuthHelper getPrincipalForPassword
INFO: No principal found for eMail admin
May 13, 2015 4:39:25 PM org.structr.websocket.command.LoginCommand processMessage
INFO: Could not login admin with admin

**Comment by cmorgner** [comment] 2015-05-13 14:44
Looks like there is no seed.zip in the directory where you start your Structr instance. Can you confirm that there is a seed.zip, or can you find and copy a seed.zip from the Structr installation? If not, you can find the seed file here: https://github.com/structr/structr/raw/master/structr-ui/seed.zip

**Comment by cmorgner** [comment] 2015-05-13 14:52
If there is a seed.zip already present, Structr has probably created some data during the first unsuccessful start attempts, so if there is a db/ directory, please delete it and try again.

**Comment by shoreflyer** [comment] 2015-05-13 14:56
I can see the seed.zip in structr-ui...

**Comment by shoreflyer** [comment] 2015-05-13 15:01
Just cloned a fresh copy from git, sorted.

**Comment by amorgner** [comment] 2015-06-12 08:48
As this seems to be fixed, I'm closing this.

**Closed by amorgner** 2015-06-12 08:48 UTC
