### ISSUE TITLE
No Resource access grant found for signature _env prevents user from being able to use UI

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#380] opened 2015-08-10 17:15 UTC
I frequently encounter a situation where the ui becomes non-responsive.  Generally while using the CRUD editor.  It's most immediately observed by the grenn flash on attribute update not flashing and snapping back to display (vs edit) appearance.

Refreshing the page produced the following result:
![image](https://cloud.githubusercontent.com/assets/8261783/9177748/eeec4332-3f47-11e5-98df-4ac92ce55f53.png)

Opening the Browser Console show that the client has received a 401 response
![image](https://cloud.githubusercontent.com/assets/8261783/9177763/16401da0-3f48-11e5-8315-b01b6efea4a4.png)

Clicking to log out, and then log back in through the /structr/ home url does not success despite providing valid credentials.

Review of the structr log confirms that a the resource access entry cannot be found at the time time when the login attempt is make from the browser.

```
Aug 10, 2015 5:05:07 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
```

This requires the user to close not just the tab, but the all windows associaed with the profile and to restart the browser to be able to log in.

This occurs on a very regular basis (>4 times an hour) and is a significant drag on productivity.

**Comment by vigorouscoding** [comment] 2015-08-11 11:07
This is a know error message. The _env resource is just a provider for version information which is displayed in the top right corner of structr-ui. (see http://localhost:8082/structr/rest/_env )

Usually this error message occurs once before login because there is no user and therefor the access is forbidden.

You can change this by adding a resource access grant ````_env```` and allow anonymous GET requests as well as authenticated GET requests.

The problem you are experiencing should not be related to this particular error message you are seeing.

I'll close this issue as the error message and the ui behaviour are not connected.
We are always looking into making structr-ui more stable - if you have further information or can provide us with a small database where we can reproduce the error we will gladly fix it.
I tried to reproduce an error like this but was not able to do so :(

**Closed by vigorouscoding** 2015-08-11 11:07 UTC

**Comment by eric-schleicher** [comment] 2015-08-12 06:29
I'll take a screencast of this since it's such a huge impediment to using the backend.  I want to find the root issue for this as it's *the* impediment to have more used on my team using backend.

**Comment by amorgner** [comment] 2015-08-12 08:07
Can you definitely exclude network issues as a the root issue?

**Comment by eric-schleicher** [comment] 2015-08-12 16:41
Here is a screen capture of the havoc this causes.  I'm entering the correct credentials.  This was taken right after the console started showing _env errors.  Clicking logout seems to succeed, but then the user cannot log back in through the main backend dialog until entire browser session is closed and then re-opened.

[![pic](http://img.youtube.com/vi/ibIkh64D4yg/0.jpg)](http://youtu.be/ibIkh64D4yg)


the following is the log for the same period:
```
Aug 12, 2015 4:19:39 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
2015-08-12 16:19:39.516:WARN:osw.StructrWebSocket:qtp2407964-710: Unhandled Error (closing con
java.lang.NullPointerException
        at org.structr.schema.action.ActionContext.<init>(ActionContext.java:72)
        at org.structr.schema.action.Actions.execute(Actions.java:86)
        at org.structr.schema.action.Actions.execute(Actions.java:81)
        at org.structr.dynamic.User.onModification(User.java:86)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModi
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:82
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:106)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(Je
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(Simple
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(Abstrac
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(Jett
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(Abstrac
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(Extensio
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(Abstrac
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(Abstra
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Aug 12, 2015 4:21:00 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
Aug 12, 2015 4:21:05 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
2015-08-12 16:21:05.993:WARN:osw.StructrWebSocket:qtp2407964-463: Unhandled Error (closing connection)
java.lang.NullPointerException
        at org.structr.schema.action.ActionContext.<init>(ActionContext.java:72)
        at org.structr.schema.action.Actions.execute(Actions.java:86)
        at org.structr.schema.action.Actions.execute(Actions.java:81)
        at org.structr.dynamic.User.onModification(User.java:86)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModificationState.java:                                                                                         248)
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:82)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:106)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDri                                                                                         ver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69                                                                                         )
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:6                                                                                         4)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDrive                                                                                         r.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:1                                                                                         60)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnectio                                                                                         n.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnecti                                                                                         on.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Aug 12, 2015 4:21:08 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
2015-08-12 16:21:08.887:WARN:osw.StructrWebSocket:qtp2407964-463: Unhandled Error (closing connection)
java.lang.NullPointerException
        at org.structr.schema.action.ActionContext.<init>(ActionContext.java:72)
        at org.structr.schema.action.Actions.execute(Actions.java:86)
        at org.structr.schema.action.Actions.execute(Actions.java:81)
        at org.structr.dynamic.User.onModification(User.java:86)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModificationState.java:                                                                                         248)
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:82)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:106)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDri                                                                                         ver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69                                                                                         )
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:6                                                                                         4)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDrive                                                                                         r.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:1                                                                                         60)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnectio                                                                                         n.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnecti                                                                                         on.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Aug 12, 2015 4:21:18 PM org.structr.web.resource.LoginResource doPost
INFO: Login successful: f02e59a47dc9492da3e6cb7fb6b3ac25
Aug 12, 2015 4:23:52 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
Aug 12, 2015 4:23:55 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
2015-08-12 16:23:55.189:WARN:osw.StructrWebSocket:qtp2407964-435: Unhandled Error (closing connection)
java.lang.NullPointerException
        at org.structr.schema.action.ActionContext.<init>(ActionContext.java:72)
        at org.structr.schema.action.Actions.execute(Actions.java:86)
        at org.structr.schema.action.Actions.execute(Actions.java:81)
        at org.structr.dynamic.User.onModification(User.java:86)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModificationState.java:                                                                                         248)
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:82)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:106)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDri                                                                                         ver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69                                                                                         )
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:6                                                                                         4)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDrive                                                                                         r.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:1                                                                                         60)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnectio                                                                                         n.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnecti                                                                                         on.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Aug 12, 2015 4:24:05 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
Aug 12, 2015 4:24:12 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
2015-08-12 16:24:12.211:WARN:osw.StructrWebSocket:qtp2407964-435: Unhandled Error (closing connection)
java.lang.NullPointerException
        at org.structr.schema.action.ActionContext.<init>(ActionContext.java:72)
        at org.structr.schema.action.Actions.execute(Actions.java:86)
        at org.structr.schema.action.Actions.execute(Actions.java:81)
        at org.structr.dynamic.User.onModification(User.java:86)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModificationState.java:                                                                                         248)
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:82)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:106)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDri                                                                                         ver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69                                                                                         )
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:6                                                                                         4)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDrive                                                                                         r.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:1                                                                                         60)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnectio                                                                                         n.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnecti                                                                                         on.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Aug 12, 2015 4:24:42 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
Aug 12, 2015 4:24:45 PM org.structr.web.auth.UiAuthenticator checkResourceAccess
INFO: No resource access grant found for signature _env.
2015-08-12 16:24:45.169:WARN:osw.StructrWebSocket:qtp2407964-660: Unhandled Error (closing connection)
java.lang.NullPointerException
        at org.structr.schema.action.ActionContext.<init>(ActionContext.java:72)
        at org.structr.schema.action.Actions.execute(Actions.java:86)
        at org.structr.schema.action.Actions.execute(Actions.java:81)
        at org.structr.dynamic.User.onModification(User.java:86)
        at org.structr.core.graph.GraphObjectModificationState.doInnerCallback(GraphObjectModificationState.java:                                                                                         248)
        at org.structr.core.graph.ModificationQueue.doInnerCallbacks(ModificationQueue.java:82)
        at org.structr.core.graph.TransactionCommand.commitTx(TransactionCommand.java:106)
        at org.structr.core.graph.Tx.success(Tx.java:69)
        at org.structr.websocket.StructrWebSocket.onWebSocketText(StructrWebSocket.java:207)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDri                                                                                         ver.java:128)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69                                                                                         )
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:6                                                                                         4)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDrive                                                                                         r.java:122)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:1                                                                                         60)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnectio                                                                                         n.java:628)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnecti                                                                                         on.java:476)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by vigorouscoding** [comment] 2015-08-12 20:47
Thank you - with the video + log I was able to successfully reproduce the issue and fix it

the fix is in master and will be included in the next snapshot.

**Comment by eric-schleicher** [comment] 2015-08-12 23:55
Hallelulah!

**Comment by eric-schleicher** [comment] 2015-08-14 06:25
@vigorouscoding, any idea when the next snapshot will be made avail on https://oss.sonatype.org?

**Comment by amorgner** [comment] 2015-08-17 10:38
Snapshot # 86 was just released: https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/1.1-SNAPSHOT/
