### ISSUE TITLE
HTML meshing doesn't agree with AngularJS

### ISSUE THREAD

**Issue by LeeSandberg** [structr/structr#401] opened 2015-10-14 08:39 UTC
When tring to end Angularjs code snibbit with a HTML tag generated from Structrs HTML rendering, it doesn't work.

More delibrate design for support off Angularjs is needed to make use of AngularJS with Structr, 
As is it does not work with full AngularJS/Structr development.

**Comment by amorgner** [comment] 2015-10-14 08:42
Structr renders HTML5-compliant HTML code. Could you please describe exactly what the problem is? Which HTML tag are you referring to?

**Comment by LeeSandberg** [comment] 2015-10-14 09:40
Hi Axel

I was using ng-repeat I think (it's a while back now) and I nested it with
tags from Structr-UI / or closed the ng-repeat with a Structr-UI HTML tag.
It was just not working as You would expect.

In guess AngularJS rendering of the page and Structrs rendering of the page
has to be in a good order.

I would expect Structr renders first with the Angularjs stuff and then the
Angularjs render should take all that Structr has render and rerender the
HTML page with what it is doing with the page.

Just as I think I am not so good at this things, but I tested simple
Angularjs stuff and had a hard time marry hard coded Anguljs code snibbits
with Structr-UIs HTML tags.

Having some structr HTML tags repeated with Angular ng-repeat or ending a
ng-repeat with a Structr-UI HTML tag was not working.

I really like both Structr and Angularjs, so hopefully we can use them
together full-on...

You want to be agnostic to Angularjs and other solutions, thats good in a
way. I like other solutions as well.
But it can't be an excuse not to marry Angularjs and other solutions to
work with Structr. But all in good time, I just want You to report my
findings and see if there is work arounds or
possibly something that can be fixed easilly.


Regards

Lee Sandberg

**Comment by amorgner** [comment] 2015-10-14 10:01
I think you need to clearly separate between Structr's server-side context and AngularJS (or any other client-side JS framework). It's a perfectly valid and working approach to use both together.

Structr creates HTML markup on the server. You can repeat any HTML element in a Structr page by applying a query and a data key. Once the HTML content is streamed to the browser client, it's up to the client-side logic to manipulate the DOM tree in the browser instance.

At the moment, there's only one way to create custom elements in Structr, namely by using Content or Template nodes with your own HTML markup in it.

Please note: Instead of ``ng-repeat`` you need to write ``data-ng-repeat`` to be HTML5-compliant.

As this is not a bug or feature request for Structr but rather a discussion, I'll close this issue. Please use our mailing list for topics and questions like this, thank you.

**Closed by amorgner** 2015-10-14 10:01 UTC

**Comment by LeeSandberg** [comment] 2015-10-14 12:18
OK I added this as a discussion on the forum.

**Comment by eric-schleicher** [comment] 2015-10-15 19:21
per angular's documentation, they admin that ngRepeat and ng-repeat are not
technically correct attribute names as they aren't compliant with HTML5
spec.

data-ng-repeat is the formally correct directive name to use.
